### ISSUE TITLE
Kokkos adding CUDA Toolkit dep unnecessarily?

### ISSUE THREAD

**Issue by vincentmr** [conda-forge/kokkos-feedstock#23]
### Comment:

The PennyLane [feedstock](https://github.com/conda-forge/pennylane-feedstock) recipe includes Kokkos and Kokkos-kernels. The Lightning subpackage expects the SERIAL backend, although OPENMP might be there without impacting the build. After adding the CUDA backend however, the build fails because `libcuda.so` is not found. This happens either during build, when the new package with the CUDA backend is pulled, or during tests, when the new package is pulled even though the old package was used to build. I'm thus wondering, does it mean that all packages with Kokkos as a dependency now have to have CUDA-variants builds, even though they are not using CUDA whatsoever?

**Comment by carterbox** [comment]
No, they can depend on the non-CUDA build variant.

**Comment by vincentmr** [comment]
Thanks, makes sense. I wonder why the test section pulled the CUDA variant.

**Comment by carterbox** [comment]
It shouldn't be possible to install the CUDA variant in an environment without the `__cuda` virtual package.

**Comment by carterbox** [comment]
@jakirkham, how do we prevent conda from installing the CUDA variant in non-`__cuda` environments?

**Comment by vincentmr** [comment]
For example, I have this issue [here](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/735235/logs/94). I have `CUDA_VERSION=None`, etc. and I build with Kokkos-3.7.01 (a workaround for now since it's trying to use the CUDA variant), but in the tests, it is still installing Kokkos-3.7.02 with `cudatoolkit==11.8.0-h37601d7_11`.

**Comment by carterbox** [comment]
Lemme know if #24 fixed issues with kokkos 3.x. If not, we may need to mark some packages as broken. If so, then I'll port the changes to kokkos 4.

**Comment by vincentmr** [comment]
#24 fixes the issue with Kokkos 3.x. Thanks a bunch @carterbox
