### ISSUE TITLE
HIP support

### ISSUE THREAD

**Issue by Frayzen** [conda-forge/kokkos-feedstock#39]
### This fundable has not been submitted yet.

- [x] This fundable has not been submitted yet.

### Motivation

Hello,

Is there any plan to support Kokkos build with HIP for all of the AMD users any soon ?
I am not really a recipe builder by the way, just a casual user. I heard that building recipes based on GPU is something else, but I don't know more about it.

Sorry if the question seems out of context.

Keep up with the good work !

### Expected result

A new version of the recipe including a working version of Kokkos supporting HIP

### Work items

- Dispose of a machine with AMD/Intel GPU I guess...
- Update the dependencies accordingly
- Adapt the recipe and the cmake tags
- Create a new conda package for Kokkos-HIP

### References

- https://kokkos.org/kokkos-core-wiki/ProgrammingGuide/Compiling.html

**Comment by carterbox** [comment]
AFAIK, the ROCm toolchain is unmaintained on our channel, so that's why we don't build for ROCm. In other words, we don't have the appropriate build tools / infrastructure to target HIP.

**Comment by Frayzen** [comment]
I confirm after some trials that conda-forge ROCm toolchain is not mature enough to be considered usable as it is. Hopefully, it gets better soon.
I can close the issue then, thank you for the explanation.
